### ISSUE TITLE
[question] full mindboggle pipeline as BIDS app?

### ISSUE THREAD

**Issue by PeerHerholz** [BIDS-Apps/mindboggle#14]
Hey there,

I was wondering if there are any plans to make the complete mindboggle pipeline available as a BIDS app? More precisely, running mindboggle123 on a BIDS input to create an output like:

```
bids_dir/
   derivatives/
      mindboggle/
        freesurfer/
          sub-*/
             mri/ 
             label/
             surf/
        ants/
          sub-*/
              antsBrainSegmentation.nii.gz
              antsCorticalThickness.nii.gz
        mindboggled/
          sub-*/
               exploded/
               features/
               labels/
```
Would that be an useful feature people might be interested in?

Best, Peer

**Comment by akeshavan** [comment]
The current version of this app already runs mindboggle123!

**Comment by PeerHerholz** [comment]
Hey @akeshavan,

thank you very much for your answer. 

Checked the code, should've done that first. Sorry.
Just to be sure: the [docker section within the readme.md](https://github.com/BIDS-Apps/mindboggle#docker) says that the mindboggle BIDS app assumes that the freesurfer BIDS app has been run. If I understood it right, that shouldn't be necessary if the app runs mindboogle123!? Is that not up to date or am I not getting it?

Best and thanks again, Peer

**Comment by akeshavan** [comment]
Ah, the README is not up to date! Sorry about that.

**Comment by PeerHerholz** [comment]
Okay, coolio. No worries. 
Thx for your help. I'm closing this.
