### ISSUE TITLE
Provide example dataset with Freesurfer inputs

### ISSUE THREAD

**Issue by chrisfilo** [BIDS-Apps/mindboggle#3]

**Comment by binarybottle** [comment]
I refer to example (FreeSurfer + ANTs) input data (https://osf.io/8cf5z/) for Mindboggle in http://mindboggle.readthedocs.io/en/latest/ 

"To run Mindboggle, you must first preprocess brain MR image data (see Preprocessing below). To get up and running with the following examples, download and unzip the mindboggle_input_example.zip directory (450 MB), which contains some example preprocessed data. More example input and output data can be found on Mindboggle’s examples osf.io site."

**Comment by chrisfilo** [comment]
Here's a dataset with precomputed FreeSurfer: https://googledrive.com/host/0B2JWN60ZLkgkMEw4bW5VUUpSdFU/ds114_test1_with_freesurfer.tar.gz @akeshavan
